name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢提出功能建议！请填写以下信息帮助我们理解你的需求。
        Thank you for suggesting a feature! Please fill out the information below to help us understand your needs.

  - type: textarea
    id: problem
    attributes:
      label: 相关问题 / Related Problem
      description: 这个功能要解决什么问题？/ What problem does this feature solve?
      placeholder: 描述你遇到的问题或需求 / Describe the problem or need you're facing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 期望解决方案 / Desired Solution
      description: 你希望这个功能如何实现？/ How would you like this feature to be implemented?
      placeholder: 清晰简洁地描述你希望的功能 / A clear description of the feature you want
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案 / Alternatives
      description: 你考虑过的其他解决方案 / Other solutions you've considered
      placeholder: 描述你考虑过的其他方法 / Describe other approaches you've considered

  - type: textarea
    id: use_case
    attributes:
      label: 使用场景 / Use Case
      description: 具体的使用场景或例子 / Specific use cases or examples
      placeholder: 提供具体的使用场景或例子 / Provide specific use cases or examples

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单 / Checklist
      description: 在提交之前，请确认以下事项 / Before submitting, please confirm the following
      options:
        - label: 我已经搜索了现有的 issues 和功能请求 / I have searched existing issues and feature requests
          required: true
        - label: 这个功能对大多数用户有价值 / This feature would be valuable to most users
          required: true
        - label: 我愿意协助实现这个功能 / I am willing to help implement this feature
          required: false